config/routes.rb
Todoapp::Application.routes.draw do
  resources :todos
  resources :logdatas do
    get 'delete', on: :collection
  end

  root :to => 'todos#index'
 

end

app/models/logdata.rb
class Logdata < ActiveRecord::Base
  attr_accessible :modification, :event

  def self.start_logging(content, event)
    Logdata.create!(:modification => content, :event => event)
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :content, :done, :order

  validates :content, :presence => true,
  			:length => {:minimum => 2}

  def add_log(event)
  	Logdata.start_logging(self.content, event)
  end
end

app/models/todo_observer.rb
class TodoObserver < ActiveRecord::Observer
	def after_create(todo)
       todo.add_log('creating')
    end

    def after_update(todo)
       todo.add_log('updating')
    end

    def after_destroy(todo)
       todo.add_log('destroing')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logdatas_controller.rb
class LogdatasController < ApplicationController
	def index
      @logs = Logdata.find(:all)
    end

    def delete
      Logdata.destroy_all()
      respond_to do |format|
        format.js # delete.js.erb
      end
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(params[:todo])

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
        #Logdata.start_logging(@todo.content, 'creating')
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
        #Logdata.start_logging(@todo.content, 'updating')
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    #Logdata.start_logging(@todo.content, 'deleting')

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logdatas_helper.rb
module LogdatasHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="title">
  <h1>Todos</h1>
</div>

  <%= yield %>

</body>
</html>

app/views/logdatas/_form.html.erb
Log file is empthy

app/views/logdatas/delete.js.erb
$('.main').html('<%= escape_javascript(render 'form') %>');

app/views/logdatas/index.html.erb
<%= link_to "Main page", root_path %>

<div class='main'>
  <table id='table_log'>
    <%@logs.each do |l|%>
	  <tr>
	    <td ><%= l.modification %></td>
	    <td ><%= l.event %></td>
	    <td ><%= l.created_at %></td>
	  </tr>
    <% end%>
  </table>
</div>

<%= link_to "Clear logging", delete_logdatas_path, :remote => true %>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :done %><br />
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div id="todoapp">

  <div id="create-todo">
    <%= text_field_tag "new-todo"%>
    <%= link_to "", "#",  :id => 'hidden_click'%>
  </div>

  <div id="main">
    <ul id="todo-list" name="todo-list">
    </ul>
  </div>

  <div id='footer'>
  	<ul id="todo-stats">
	  </ul>
    <div id ='log'>
      <%= link_to 'Logging list', logdatas_path%>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @todo.content %>
</p>

<p>
  <b>Order:</b>
  <%= @todo.order %>
</p>

<p>
  <b>Done:</b>
  <%= @todo.done %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>